version: '3.8'

services:
  streamvault-pro:
    build:
      context: .
      dockerfile: Dockerfile
    image: tmwgsicp/streamvault-pro:latest
    container_name: streamvault-pro
    restart: unless-stopped
    
    ports:
      - "8080:8080"
    
    volumes:
      - ./downloads:/home/streamvault/app/downloads
      - ./config:/home/streamvault/app/config
      - ./logs:/home/streamvault/app/logs
    
    environment:
      - PLATFORM=web
      - HOST=0.0.0.0
      - PORT=8080
      - TZ=Asia/Shanghai
    
    env_file:
      - .env
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    
    # Network configuration
    networks:
      - streamvault-network

networks:
  streamvault-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16