name: 🐛 Bug Report | Bug反馈
description: Create a bug report to help us improve StreamVault Pro | 创建Bug报告帮助我们改进StreamVault Pro
title: "[Bug] "
labels: ["bug", "triage"]
assignees: ["tmwgsicp"]

body:
  - type: markdown
    attributes:
      value: |
        感谢您报告Bug！请详细填写以下信息以帮助我们快速定位和解决问题。
        Thank you for reporting a bug! Please fill out the following information in detail to help us quickly locate and resolve the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: 📋 检查清单 | Checklist
      description: 请确认您已经完成以下步骤 | Please confirm you have completed the following steps
      options:
        - label: 我已搜索现有的Issues，确认这是一个新问题 | I have searched existing issues and confirmed this is a new problem
          required: true
        - label: 我已阅读文档和FAQ | I have read the documentation and FAQ
          required: true
        - label: 我使用的是最新版本 | I am using the latest version
          required: false

  - type: textarea
    id: description
    attributes:
      label: 🐛 问题描述 | Bug Description
      description: 清晰简洁地描述这个bug | A clear and concise description of what the bug is
      placeholder: 例如：录制某个平台时出现错误... | e.g., Error occurs when recording from a specific platform...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔄 重现步骤 | Steps to Reproduce
      description: 详细描述如何重现这个问题 | Detail how to reproduce this issue
      placeholder: |
        1. 打开应用程序
        2. 添加直播间URL
        3. 点击开始录制
        4. 出现错误...
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ 期望行为 | Expected Behavior
      description: 描述您期望发生的行为 | Describe what you expected to happen
      placeholder: 应该正常开始录制... | Should start recording normally...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ 实际行为 | Actual Behavior
      description: 描述实际发生的行为 | Describe what actually happened
      placeholder: 显示错误信息... | Shows error message...
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 💻 操作系统 | Operating System
      description: 选择您的操作系统 | Select your operating system
      options:
        - Windows 10
        - Windows 11
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Web Browser
        - Docker
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 📊 版本信息 | Version Information
      description: StreamVault Pro版本号 | StreamVault Pro version number
      placeholder: 例如：v2.0.0 | e.g., v2.0.0
    validations:
      required: true

  - type: dropdown
    id: install_method
    attributes:
      label: 📦 安装方式 | Installation Method
      description: 您是如何安装的 | How did you install it
      options:
        - 预构建版本 | Pre-built release
        - 源码安装 | Source installation
        - Docker
        - Web版本 | Web version
    validations:
      required: true

  - type: textarea
    id: streaming_platform
    attributes:
      label: 📺 直播平台 | Streaming Platform
      description: 出现问题的直播平台（如适用）| The streaming platform where the issue occurs (if applicable)
      placeholder: 例如：抖音、B站、TikTok等 | e.g., Douyin, Bilibili, TikTok, etc.

  - type: textarea
    id: logs
    attributes:
      label: 📋 错误日志 | Error Logs
      description: 请粘贴相关的错误日志 | Please paste relevant error logs
      placeholder: |
        粘贴日志内容...
        Paste log content...
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 截图 | Screenshots
      description: 如果适用，请添加截图来解释问题 | If applicable, add screenshots to help explain your problem
      placeholder: 拖拽图片到这里... | Drag images here...

  - type: textarea
    id: additional
    attributes:
      label: 📝 其他信息 | Additional Information
      description: 其他可能有助于解决问题的信息 | Any other information that might help resolve the issue
      placeholder: 例如：特定配置、网络环境等... | e.g., specific configuration, network environment, etc...

  - type: dropdown
    id: priority
    attributes:
      label: 🚨 优先级 | Priority
      description: 这个问题的严重程度 | The severity of this issue
      options:
        - 低 - 不影响核心功能 | Low - Does not affect core functionality
        - 中 - 影响部分功能 | Medium - Affects some functionality
        - 高 - 影响核心功能 | High - Affects core functionality
        - 紧急 - 应用无法使用 | Critical - Application is unusable
      default: 1

  - type: checkboxes
    id: contact
    attributes:
      label: 📧 联系方式 | Contact
      description: 如需要，我们如何联系您 | How can we contact you if needed
      options:
        - label: 我同意通过GitHub进行后续沟通 | I agree to follow-up communication via GitHub
          required: false
        - label: 我可以提供更多信息来帮助调试 | I can provide more information to help with debugging
          required: false 